name: Test GitHub Refs

on:
  push:
    branches: 
      - main

  pull_request:
    types:
      - closed
    branches: 
      - main
  
  workflow_dispatch:

jobs:
 
  test_github_refs:

    runs-on: ubuntu-latest

    steps:
      - name: Display branch info
        id: display_branch_info
        run: |
          echo "printing github.ref --- ${{ github.ref }}"
          echo "printing github.ref_name --- ${{ github.ref_name }}"
          echo "printing github.head_ref --- ${{ github.head_ref }}"
          echo "printing github.base_ref --- ${{ github.base_ref }}"
          echo "printing github.event_name --- ${{ github.event_name }}"
